services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    ports:
      - "6001:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
